---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: counterblock-base
  labels:
    app: counterblock-base
spec:
  ports:
  - port: 14000
  selector:
    app: ctp
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: counterblock-base
spec:
  serviceName: counterblock-base
  replicas: 1
  template:
    metadata:
      labels:
        app: ctp
      annotations:
        pod.beta.kubernetes.io/init-containers: '[]'
    spec:
      containers:
      - name: ctpbase
        imagePullPolicy: IfNotPresent
        image: counterparty/counterblock
        ports:
        ports:
        - containerPort: 14100
        - containerPort: 14101
        - containerPort: 14102
        env:
        - name: PARAMS
          value: --config-file=/root/.config/counterblock/server.testnet.conf  
        volumeMounts:
          - mountPath: /counterblock
            name: counterblock
          - mountPath: /root/.config/counterblock
            name: counterblock-config
          - mountPath: /root/.local/share/counterblock
            name: counterblock-data
      
  
  volumeClaimTemplates:
  - metadata:
      name: counterblock
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: counterblock-config
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: counterblock-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
