---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: counterparty
  labels:
    app: counterparty
spec:
  ports:
  - port: 46656
    name: p2p
  - port: 46657
    name: rpc
  clusterIP: None
  selector:
    app: ctp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ctp-config
data:
  seeds: "ctp-0,ctp-1,ctp-2,ctp-3"
  validators: "ctp-0,ctp-1,ctp-2,ctp-3"
  validator.power: "10"
  genesis.json: |-
    {
      "genesis_time": "2016-04-26T22:00:00Z",
      "chain_id": "chain-IdealX",
      "validators": [],
      "app_hash": ""
    }
  pub_key_nginx.conf: |-
    server {
      listen 80 default_server;
      listen [::]:80 default_server ipv6only=on;
      location /pub_key.json { root /usr/share/nginx/; }
      location /app_pub_key.json { root /usr/share/nginx/; }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: app-config
    data:
        genesis.json: |-
          {
            "chain_id": "chain-idealX",
            "app_options": {
              "accounts": [
                {
                  "pub_key": "ctp-0",
                  "coins": [
                    {
                      "denom": "mycoin",
                      "amount": 1000000000
                      }
                      ]
                      },
                      {
                        "pub_key": "ctp-1",
                        "coins": [
                          {
                            "denom": "mycoin",
                            "amount": 1000000000
                            }
                        ]
                        },
                        {
                          "pub_key": "ctp-2",
                          "coins": [
                            {
                              "denom": "mycoin",
                              "amount": 1000000000
                              }
                              ]
                              },
                              {
                                "pub_key": "ctp-3",
                                "coins": [
                                  {
                                    "denom": "mycoin",
                                    "amount": 1000000000
                                    }
                                    ]
                                    }
                                    ]
                                  }
                            }
                            ---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ctp-budget
spec:
  selector:
    matchLabels:
      app: ctp
  minAvailable: 2
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ctp
spec:
  serviceName: counterparty
  replicas: 4
  template:
    metadata:
      labels:
        app: ctp
      annotations:
        pod.beta.kubernetes.io/init-containers: '[]'
    spec:
      containers:
      - name: ctpbitcoin
        imagePullPolicy: IfNotPresent
        image: counterparty/bitcoin
        ports:
        - containerPort: 18332
        env:
          - name: PARAMS
          value: -conf=/root/.bitcoin-config/bitcoin.testnet.conf
       

      volumes:
      - name: tmconfigdir
        configMap:
          name: ctp-config
      - name: appconfigdir
        configMap:
          name: app-config
      - name: socksdir
        emptyDir: {}

  volumeClaimTemplates:
  - metadata:
      name: tmdir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: appdir
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 12Mi
