---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: counterparty-server
  labels:
    app: counterparty-server
spec:
  ports:
  - port: 14000
  selector:
    app: ctp
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: counterparty-server
spec:
  serviceName: counterparty-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ctp
      annotations:
        pod.beta.kubernetes.io/init-containers: '[]'
    spec:
      containers:
      - name: ctpbase
        imagePullPolicy: IfNotPresent
        image: counterparty/counterparty-server
        workingDir: /counterparty-cli
        ports:
        - containerPort: 14000
        env:
        - name: PARAMS
          value: --config-file=/root/.config/counterparty/server.testnet.conf          
        volumeMounts:
          - mountPath: /root/.config/counterparty
            name: counterparty-config
          - mountPath: /root/.local/share/counterparty
            name: counterparty-data
      
  
  volumeClaimTemplates:
  - metadata:
      name: counterparty-config
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: counterparty-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi

