---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: counterparty-bitcoin
  labels:
    app: counterparty-bitcoin
spec:
  ports:
  - port: 18332
  selector:
    app: ctp
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ctp-budget
spec:
  selector:
    matchLabels:
      app: counterparty-bitcoin
  minAvailable: 2
---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: counterparty-bitcoin
spec:
  serviceName: counterparty-bitcoin
  replicas: 2
  template:
    metadata:
      labels:
        app: ctp
      annotations:
        pod.beta.kubernetes.io/init-containers: '[]'
    spec:
      containers:
      - name: ctpbitcoin
        imagePullPolicy: IfNotPresent
        image: counterparty/bitcoin
        ports:
        - containerPort: 18332
        env:
        - name: PARAMS
          value: -conf=/root/.bitcoin-config/bitcoin.testnet.conf  
        volumeMounts:
          - mountPath: /root/.bitcoin-config
            name: bitcoin-config
          - mountPath: /root/.bitcoin/
            name: bitcoin-data
      
  
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: bitcoin-config
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 12Mi
